services:
  # SSH server for testing SSH protocol operations
  odi-ssh-server:
    image: alpine:latest
    container_name: odi-ssh-server
    ports:
      - "2222:22"
    volumes:
      - ./.docker/ssh-repos:/repos
      - ./.docker/ssh-keys:/keys
    environment:
      - SSH_ENABLE_PASSWORD_AUTH=yes
      - SSH_USERS=odiuser:1000:1000
    command: |
      sh -c '
        apk add --no-cache openssh-server openssh-keygen shadow &&
        ssh-keygen -A &&
        mkdir -p /repos /keys &&
        adduser -D -s /bin/sh -u 1000 odiuser &&
        echo "odiuser:odipass" | chpasswd &&
        sed -i "s/#PasswordAuthentication.*/PasswordAuthentication yes/" /etc/ssh/sshd_config &&
        sed -i "s/#PubkeyAuthentication.*/PubkeyAuthentication yes/" /etc/ssh/sshd_config &&
        sed -i "s/#PermitRootLogin.*/PermitRootLogin no/" /etc/ssh/sshd_config &&
        mkdir -p /home/odiuser/.ssh &&
        chmod 700 /home/odiuser/.ssh &&
        chown -R odiuser:odiuser /home/odiuser/.ssh &&
        chown -R odiuser:odiuser /repos &&
        /usr/sbin/sshd -D -e
      '
    networks:
      - odi-test

  # HTTPS server for testing HTTPS protocol operations
  odi-https-server:
    image: alpine:latest
    container_name: odi-https-server
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./.docker/https-repos:/var/www/repos
      - ./.docker/ssl-certs:/etc/ssl/certs/odi
    command: |
      sh -c '
        apk add --no-cache apache2 apache2-ssl openssl git &&
        mkdir -p /var/www/repos /etc/ssl/certs/odi /var/log/apache2 /run/apache2 &&
        
        # Generate self-signed certificate for testing
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /etc/ssl/certs/odi/server.key \
          -out /etc/ssl/certs/odi/server.crt \
          -subj "/C=US/ST=Test/L=Test/O=ODI/CN=localhost" &&
        
        # Modify the default Apache config to add SSL support
        cp /etc/apache2/httpd.conf /etc/apache2/httpd.conf.bak &&
        echo "ServerName localhost" >> /etc/apache2/httpd.conf &&
        echo "LoadModule ssl_module modules/mod_ssl.so" >> /etc/apache2/conf.d/ssl.conf &&
        echo "Listen 443 ssl" >> /etc/apache2/conf.d/ssl.conf &&
        echo "" >> /etc/apache2/conf.d/ssl.conf &&
        echo "<VirtualHost *:80>" >> /etc/apache2/conf.d/odi.conf &&
        echo "    DocumentRoot /var/www/repos" >> /etc/apache2/conf.d/odi.conf &&
        echo "    <Directory \"/var/www/repos\">" >> /etc/apache2/conf.d/odi.conf &&
        echo "        Options Indexes FollowSymLinks" >> /etc/apache2/conf.d/odi.conf &&
        echo "        AllowOverride None" >> /etc/apache2/conf.d/odi.conf &&
        echo "        Require all granted" >> /etc/apache2/conf.d/odi.conf &&
        echo "    </Directory>" >> /etc/apache2/conf.d/odi.conf &&
        echo "</VirtualHost>" >> /etc/apache2/conf.d/odi.conf &&
        echo "" >> /etc/apache2/conf.d/odi.conf &&
        echo "<VirtualHost *:443>" >> /etc/apache2/conf.d/odi.conf &&
        echo "    DocumentRoot /var/www/repos" >> /etc/apache2/conf.d/odi.conf &&
        echo "    SSLEngine on" >> /etc/apache2/conf.d/odi.conf &&
        echo "    SSLCertificateFile /etc/ssl/certs/odi/server.crt" >> /etc/apache2/conf.d/odi.conf &&
        echo "    SSLCertificateKeyFile /etc/ssl/certs/odi/server.key" >> /etc/apache2/conf.d/odi.conf &&
        echo "    <Directory \"/var/www/repos\">" >> /etc/apache2/conf.d/odi.conf &&
        echo "        Options Indexes FollowSymLinks" >> /etc/apache2/conf.d/odi.conf &&
        echo "        AllowOverride None" >> /etc/apache2/conf.d/odi.conf &&
        echo "        Require all granted" >> /etc/apache2/conf.d/odi.conf &&
        echo "    </Directory>" >> /etc/apache2/conf.d/odi.conf &&
        echo "</VirtualHost>" >> /etc/apache2/conf.d/odi.conf &&
        
        # Create some test repositories
        mkdir -p /var/www/repos/test-repo.odi &&
        echo "Test ODI repository for HTTPS testing" > /var/www/repos/test-repo.odi/README.txt &&
        echo "<html><body><h1>ODI Test Server</h1><ul><li><a href=\"test-repo.odi/\">test-repo.odi/</a></li></ul></body></html>" > /var/www/repos/index.html &&
        
        # Set permissions
        chown -R apache:apache /var/www &&
        chmod -R 755 /var/www &&
        
        # Start Apache
        httpd -D FOREGROUND
      '

  # Simple HTTP server for testing (alternative to Apache)
  odi-simple-http:
    image: alpine:latest
    container_name: odi-simple-http
    ports:
      - "8090:8000"
    volumes:
      - ./.docker/https-repos:/var/www/repos
    command: |
      sh -c '
        apk add --no-cache python3 git &&
        mkdir -p /var/www/repos/test-repo.odi &&
        echo "Test ODI repository for HTTP testing" > /var/www/repos/test-repo.odi/README.txt &&
        echo "ODI Simple HTTP Server - test-repo.odi available" > /var/www/repos/index.html &&
        cd /var/www/repos &&
        python3 -m http.server 8000
      '
    networks:
      - odi-test

  # Git server for reference/comparison (using Python HTTP server)
  git-server:
    image: alpine:latest
    container_name: odi-git-server
    ports:
      - "9418:8000"
    volumes:
      - ./.docker/git-repos:/git-repos
    command: |
      sh -c '
        apk add --no-cache git python3 &&
        mkdir -p /git-repos &&
        cd /git-repos &&
        git init --bare test-repo.git &&
        echo "ODI Git test repository" > /git-repos/test-repo.git/description &&
        echo "Git repositories available via HTTP" > /git-repos/index.html &&
        cd /git-repos &&
        python3 -m http.server 8000
      '
    networks:
      - odi-test

networks:
  odi-test:
    driver: bridge

volumes:
  ssh-repos:
  https-repos:
  git-repos:
