# Rust formatting configuration for ODI workspace
# Ensures consistent code style across all crates

# Edition and language version
edition = "2021"
version = "Two"

# Code layout
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports organization
imports_layout = "HorizontalVertical"
imports_granularity = "Crate" 
reorder_imports = true
group_imports = "StdExternalCrate"

# Function and control flow formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Advanced formatting
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true

# String formatting
format_strings = false  # Preserve string formatting
string_lit_single_line = true

# Struct and enum formatting
struct_lit_single_line = true
enum_discrim_align_threshold = 20

# Error handling
force_explicit_abi = true
normalize_comments = true
normalize_doc_attributes = true